### ISSUE TITLE
Cropping tool

### ISSUE THREAD

**Issue by georgievgeorgi** [h2020charisma/oranchada#34]
Tool that is able to crop spectra

- should it crop by x-axis values or bin number
- what happens when multiple spectra are provided (possibly with different x-axis)
- does it preserve x-axis just clear corresponding y-values or creates a cropped version of the spectra

**Comment by vedina** [comment]
there is crop widget in oranchada 0.15 
- crops by x-axis  values (that's what user would expect)
- crops each spectrum and preserve the  x-axis  ( x-axis should only be changed by dedicated widgets as resample or calibration)
